site_name: attractors
site_url: https://attractors.readthedocs.io/
site_description: A package for simulation and visualization of strange attractors.
site_author: "vdesmond"
repo_url: https://github.com/vdesmond/attractors
repo_name: vdesmond/attractors
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.ico
  font:
    text: Sora
  palette:
    scheme: slate
    primary: custom
    accent: custom
extra_css:
  - stylesheets/extra.css
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: true
            show_type_annotations: true
            members_order: source
            docstring_style: google
            show_root_toc_entry: true
            show_object_full_path: true
            show_docstring_examples: true
            show_symbol_type_toc: true
            show_symbol_type_heading: true
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
